# Generated by Django 5.1.1 on 2024-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/id/890080686/vector/no-eating-or-drinking-sign-paper-cup-with-tubule-and-hamburger-icons-in-crossed-out-red.jpg?s=612x612&w=0&k=20&c=50abocAMrItzwS2Uxzd17E78JF8En9ccn8KfLXJVzxM=', max_length=100),
        ),
    ]
